Greeting.create(message: "Welcome to my website!")
Greeting.create(message: "Hey there!")
Greeting.create(message: "Good day!")
Greeting.create(message: "Greetings #1!")
Greeting.create(message: "Greetings #2!")
